package cz.muni.ics.kypo.training.exceptions;

public enum ErrorCode {
    NO_AVAILABLE_SANDBOX, WRONG_LEVEL_TYPE, RESOURCE_NOT_FOUND, CANNOT_BE_CREATED, CANNOT_BE_MODIFIED,
    NO_NEXT_LEVEL, WRONG_PASSWORD, CANNOT_REACH_RESOURCE, PASSWORD_ALREADY_EXISTS
}
